<?php

/**
*  Include de las Clases del proyecto
**/
require(dirname(__FILE__).'/core/CodexAuth.php');  
require(dirname(__FILE__).'/core/CodexSetting.php');  
require(dirname(__FILE__).'/core/CodexHttpUriRequest.php');
require(dirname(__FILE__).'/core/CodexEntityUtils.php'); 
require(dirname(__FILE__).'/core/CodexHttpGet.php'); 
require(dirname(__FILE__).'/core/CodexHttpPost.php');  
require(dirname(__FILE__).'/core/CodexServiceClientException.php');
require(dirname(__FILE__).'/core/CodexBasicRequestLine.php');
require(dirname(__FILE__).'/core/CodexStatusLine.php');  
require(dirname(__FILE__).'/core/CodexURLEncodedUtils.php');
require(dirname(__FILE__).'/core/CodexBankProfile.php');           
require(dirname(__FILE__).'/core/CodexGsonBuilder.php'); 
require(dirname(__FILE__).'/core/CodexGson.php');    
require(dirname(__FILE__).'/core/CodexHttpResponse.php');  
require(dirname(__FILE__).'/core/CodexTransaction.php');  
require(dirname(__FILE__).'/core/CodexGatewayResponse.php');
require(dirname(__FILE__).'/core/CodexClosingReport.php');
require(dirname(__FILE__).'/core/CodexSession.php');
require(dirname(__FILE__).'/core/CodexTransactionQuery.php');    
require(dirname(__FILE__).'/core/CodexCloseableHttpClient.php'); 
require(dirname(__FILE__).'/core/CodexHttpEntity.php');    
require(dirname(__FILE__).'/core/CodexHttpUtils.php');    
require(dirname(__FILE__).'/core/CodexURI.php');
require(dirname(__FILE__).'/core/CodexDecimal.php');
require(dirname(__FILE__).'/core/CodexSignature.php');
require(dirname(__FILE__).'/core/CodexQrImage.php');   
require(dirname(__FILE__).'/core/CodexUrlEncodedFormEntity.php');   
require(dirname(__FILE__).'/core/CodexServiceClient.php');   