/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poscodex;

import comcodex.*;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.text.*;
import java.util.Date;
import java.util.LinkedList;
import java.util.TimeZone;
import java.lang.reflect.Field;

/**
 *
 * @author rogerzavala
 */
public class MainFrame extends javax.swing.JFrame {
    
    private ServiceClient serviceClient;
    private String currentToken = "";
    private boolean isDebug = true;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
       
        comcodex.Setting setting = new comcodex.Setting();
        
        
        setting.serviceUri   = "http://192.168.0.116";
        setting.servicePort  = "8300";
        setting.secretPhrase = "SECRET-1226B2-F6C759-B9ADCC-2AFB81";
        setting.clientKey    = "CCODEX-596539-259D47-BC4705-00000A";
        setting.qrServiceUri = "http://comcodex.local/image/qrImage/:token.png";
        setting.pathImage    = "/home/jcarrillo/Documents/qr/";
	setting.device       = "PC_API_TEST";
        
        
        /*
        setting.serviceUri   = "http://192.168.0.110";
        setting.servicePort  = "8082";
        setting.secretPhrase = "SECRET-39B6E2-69E352-6ACC59-A77A56";
        setting.clientKey	 = "CCODEX-57DAA2-AE6FC9-A67575-00000E";
        setting.qrServiceUri = "http://192.168.0.110:8080/image/qrImage/:token.png";
        setting.pathImage 	 = "/home/jcarrillo/Documents/qr/";
	setting.device		 = "PC_API_TEST";
        */
        /*
        
        setting.serviceUri   = "https://qa-api.paycodex.com";
        setting.servicePort  = "";
        setting.secretPhrase = "SECRET-276700-A8FBB7-8C789C-A3978F";
        setting.clientKey    = "CCODEX-5915FB-61EC74-FE5304-00000D";
        setting.qrServiceUri = "http://qa.paycodex.com/image/qrImage/:token.png";
        setting.pathImage 	 = "/home/jcarrillo/Documents/qr/";
	setting.device		 = "PC_API_TEST";
        */
        
        
        this.labelTitleAmountValue.setText( "" );
        this.labelTitleDateValue.setText( "" );
        this.labelTitleDeviceValue.setText( "" );        
        this.labelTitleConceptValue.setText( "" );
        this.labelTitleStatusValue.setText( "" );
        this.labelTitlePayerValue.setText( "" );
        this.labelTitleCardNumberValue.setText( "" );
        this.labelTitlePayerIdentityValue.setText( "" );
        this.labelTitlePayDateValue.setText( "" );  
        
        this.serviceClient = new ServiceClient(setting);
        
        // Cargar Cuenta Wallet
        DialogLoading loading = this.buildLoading();
        CustomWorker worker = new CustomWorker( CustomWorker.LOAD_BANK_PROFILE_LIST, this, loading );
        worker.execute();
        loading.setVisible(true);
        
    }
    
    
    /**
     * 
     * @return 
     */
    public ServiceClient getServiceClient()
    {
        return this.serviceClient;
    }
    
    
    /**
     * 
     * @return 
     */
    public String getCurrentToken()
    {
        return this.currentToken;
    }
    
    
    /**
     * 
     * @param token 
     */
    public void setCurrentToken(String token)
    {
        this.currentToken = token;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        buttonFilter = new javax.swing.JButton();
        textboxBeginDate = new javax.swing.JTextField();
        textboxEndDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listboxTransactions = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelQr = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        labelTitleOperation = new javax.swing.JLabel();
        labelTitleDate = new javax.swing.JLabel();
        labelTitleDevice = new javax.swing.JLabel();
        labelTitleAmount = new javax.swing.JLabel();
        labelTitleConcept = new javax.swing.JLabel();
        labelTitleStatus = new javax.swing.JLabel();
        labelTitleDateValue = new javax.swing.JLabel();
        labelTitleDeviceValue = new javax.swing.JLabel();
        labelTitleAmountValue = new javax.swing.JLabel();
        labelTitleConceptValue = new javax.swing.JLabel();
        labelTitleStatusValue = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelTitlePayInfo = new javax.swing.JLabel();
        labelTitlePayDate = new javax.swing.JLabel();
        labelTitlePayer = new javax.swing.JLabel();
        labelTitleCardNumber = new javax.swing.JLabel();
        labelTitlePayerIdentity = new javax.swing.JLabel();
        labelTitlePayDateValue = new javax.swing.JLabel();
        labelTitlePayerValue = new javax.swing.JLabel();
        labelTitleCardNumberValue = new javax.swing.JLabel();
        labelTitlePayerIdentityValue = new javax.swing.JLabel();
        buttonCreateTransaction = new javax.swing.JButton();
        buttonUpdateTransction = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonLoadTransaction = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1022, 745));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poscodex/resources/logo.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Transacciones"));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Filtros Fecha"));

        buttonFilter.setFont(new java.awt.Font("Lucida Grande", 1, 8)); // NOI18N
        buttonFilter.setText("FILTRAR");
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });

        textboxEndDate.setName(""); // NOI18N

        jLabel4.setText("Inicio");

        jLabel5.setText("Fin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textboxBeginDate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addComponent(textboxEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFilter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textboxBeginDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textboxEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFilter)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        listboxTransactions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listboxTransactions);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(152, 152, 152))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Detalle de la Transacción"));

        panelQr.setBackground(new java.awt.Color(255, 255, 255));
        panelQr.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        panelQr.setMaximumSize(new java.awt.Dimension(300, 300));
        panelQr.setMinimumSize(new java.awt.Dimension(300, 300));
        panelQr.setName(""); // NOI18N
        panelQr.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout panelQrLayout = new javax.swing.GroupLayout(panelQr);
        panelQr.setLayout(panelQrLayout);
        panelQrLayout.setHorizontalGroup(
            panelQrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );
        panelQrLayout.setVerticalGroup(
            panelQrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        labelTitleOperation.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelTitleOperation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitleOperation.setText("OPERACIÓN");

        labelTitleDate.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleDate.setText("Fecha:");

        labelTitleDevice.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleDevice.setText("Dispositivo:");

        labelTitleAmount.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleAmount.setText("Monto:");

        labelTitleConcept.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleConcept.setText("Concepto:");
        labelTitleConcept.setToolTipText("");

        labelTitleStatus.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleStatus.setText("Estatus:");

        labelTitleDateValue.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleDateValue.setText("jLabel4");

        labelTitleDeviceValue.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleDeviceValue.setText("jLabel5");

        labelTitleAmountValue.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleAmountValue.setText("jLabel6");

        labelTitleConceptValue.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleConceptValue.setText("jLabel7");
        labelTitleConceptValue.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelTitleConceptValue.setAutoscrolls(true);
        labelTitleConceptValue.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        labelTitleStatusValue.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleStatusValue.setText("jLabel8");

        labelTitlePayInfo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        labelTitlePayInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitlePayInfo.setText("DATOS PAGO");

        labelTitlePayDate.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitlePayDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTitlePayDate.setText("Fecha:");

        labelTitlePayer.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitlePayer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTitlePayer.setText("Pagador:");

        labelTitleCardNumber.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleCardNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTitleCardNumber.setText("Nº Tarjeta:");

        labelTitlePayerIdentity.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitlePayerIdentity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTitlePayerIdentity.setText("Cédula/Rif:");

        labelTitlePayDateValue.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitlePayDateValue.setText("jLabel4");

        labelTitlePayerValue.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitlePayerValue.setText("jLabel5");

        labelTitleCardNumberValue.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitleCardNumberValue.setText("jLabel6");

        labelTitlePayerIdentityValue.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        labelTitlePayerIdentityValue.setText("jLabel7");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTitleDevice)
                            .addComponent(labelTitleDate)
                            .addComponent(labelTitleAmount)
                            .addComponent(labelTitleConcept))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(labelTitleDateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelTitleStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTitleStatusValue, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelTitleConceptValue, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTitleAmountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTitleDeviceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTitleOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTitlePayInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitlePayerIdentity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTitleCardNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTitlePayer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTitlePayDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitlePayDateValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTitlePayerValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTitleCardNumberValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTitlePayerIdentityValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelTitleOperation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitleDate)
                    .addComponent(labelTitleStatus)
                    .addComponent(labelTitleDateValue)
                    .addComponent(labelTitleStatusValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitleDevice)
                    .addComponent(labelTitleDeviceValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitleAmount)
                    .addComponent(labelTitleAmountValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitleConcept)
                    .addComponent(labelTitleConceptValue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTitlePayInfo)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitlePayDateValue)
                    .addComponent(labelTitlePayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitlePayerValue)
                    .addComponent(labelTitlePayer, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitleCardNumber)
                    .addComponent(labelTitleCardNumberValue, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitlePayerIdentity)
                    .addComponent(labelTitlePayerIdentityValue))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        buttonCreateTransaction.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        buttonCreateTransaction.setText("CREAR");
        buttonCreateTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateTransactionActionPerformed(evt);
            }
        });

        buttonUpdateTransction.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        buttonUpdateTransction.setText("ACTUALIZAR");
        buttonUpdateTransction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateTransctionActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton1.setText("REVERTIR");
        jButton1.setToolTipText("");
        jButton1.setMaximumSize(new java.awt.Dimension(107, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(107, 23));
        jButton1.setName("revertTransaction"); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(107, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRevertedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(panelQr, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(buttonCreateTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdateTransction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelQr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonUpdateTransction, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonCreateTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        buttonLoadTransaction.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        buttonLoadTransaction.setText(">>");
        buttonLoadTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadTransactionActionPerformed(evt);
            }
        });

        jButton2.setText("Cierre");
        jButton2.setName("cierre"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCierreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(8, 8, 8)
                .addComponent(buttonLoadTransaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButton2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(buttonLoadTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * 
     */
    public void loadTransactionList()
    {
        
            TransactionQuery query = new TransactionQuery();
            
            try 
            {
                Transaction[] transactions = this.serviceClient.listTransactions(query );
                
                TransactionListBoxModel model = new TransactionListBoxModel();
                model.fill(transactions);
                
                this.listboxTransactions.setModel(model);
                
            } 
            catch (ServiceClientException ex) 
            {
                 this.showError("Error obteniendo las lista de transacciones del perfil.", ex.getMessage() );
            }
    }
    
    /**
     * 
     * @param evt 
     */
    private void buttonLoadTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadTransactionActionPerformed
        // TODO add your handling code here:
        if( this.listboxTransactions.getSelectedIndex() >= 0 )
        {
            TransactionDisplayItem transactionDisplayItemSelected = (TransactionDisplayItem)this.listboxTransactions.getSelectedValue();
            Transaction transaction = transactionDisplayItemSelected.getValue();

            if( transaction != null )
            {
                this.currentToken = transaction.token;

                DialogLoading loading = this.buildLoading();
                CustomWorker worker = new CustomWorker( CustomWorker.SHOW_TRANSACTION, this, loading );
                worker.execute();
                
                loading.setVisible(true);
            }

        }

    }//GEN-LAST:event_buttonLoadTransactionActionPerformed

    
    /**
     * 
     * @param status
     * @return 
     */
    public String getLabelStatus(int status)
    {
        String result = "En espera";
        
        switch(status)
        {
            case Transaction.STATUS_REJECTED:
                result = "Rechazada";
                break;   
            case Transaction.STATUS_FAIL:
                result = "Falla Servicio";
                break;   
            case Transaction.STATUS_OK:
                result = "Pagada";
                break; 
            case Transaction.STATUS_REVERT:
                result = "Revertida";
                break;
        }
      
        return result;
    }
    
    /**
     * 
     */
    public void showTransaction() throws ServiceClientException
    {
        if( !"".equals(this.currentToken) )
        {
            Transaction transaction;

            transaction = this.serviceClient.retrieveTransaction(this.currentToken);

            try
            {

                this.labelTitleAmountValue.setText( transaction.amount.number.toString() + "." + transaction.amount.decimal.toString() );
                this.labelTitleDateValue.setText(transaction.openDate.toString() );
                this.labelTitleDeviceValue.setText(transaction.device );
                this.labelTitleConceptValue.setText(transaction.concept );
                
                this.labelTitleStatusValue.setText(     this.getLabelStatus( transaction.status ) );
                
                if( transaction.payed )
                {
                    
                    this.labelTitlePayerValue.setText(          transaction.payedCardHolder );
                    this.labelTitleCardNumberValue.setText(     transaction.payedCardNumber.substring( transaction.payedCardNumber.length()-8 ).toUpperCase() );
                    this.labelTitlePayerIdentityValue.setText(  transaction.payedIdentity );
                    this.labelTitlePayDateValue.setText(        transaction.payedDate.toString() );     
                }
                else
                {
                    this.labelTitlePayerValue.setText( "" );
                    this.labelTitleCardNumberValue.setText( "" );
                    this.labelTitlePayerIdentityValue.setText( "" );
                    this.labelTitlePayDateValue.setText( "" );
                }

                String imagePath = this.serviceClient.getQrImage(transaction);
                ImageIcon imageIcon = new ImageIcon(imagePath);

                Graphics g = this.panelQr.getGraphics();
                g.clearRect(0, 0, this.panelQr.getWidth(), this.panelQr.getHeight());
                g.drawImage( imageIcon.getImage(), 0, 0, Color.WHITE, null );
            } 
            catch (Exception ex) 
            {
                 this.showError("Error showTransaction ", ex.getMessage() );
            }

        }

    }
    
    
    /**
     * 
     * @param message
     * @param sourceMessage 
     */
    public void showError( String message, String sourceMessage )
    {
        if( this.isDebug )
            this.showError(sourceMessage); 
        else
            this.showError(message); 
    }
	
    /**
     * 
     * @param message 
     */
    public void showError(String message) {
        JOptionPane.showMessageDialog(this, message);
    }    
    
    /**
     * 
     * @param evt 
     */
    private void buttonUpdateTransctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateTransctionActionPerformed
        // TODO add your handling code here:        
        DialogLoading loading = this.buildLoading();
        CustomWorker worker = new CustomWorker( CustomWorker.SHOW_TRANSACTION, this, loading );
        worker.execute();
        loading.setVisible(true);
    }//GEN-LAST:event_buttonUpdateTransctionActionPerformed

    
    /**
     * 
     * @param evt 
     */
    private void buttonCreateTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateTransactionActionPerformed
        // TODO add your handling code here:
 
        DialogTransaction d = new DialogTransaction(this, true);
        d.setLocationRelativeTo(this);
        d.setVisible(true); 

    }//GEN-LAST:event_buttonCreateTransactionActionPerformed

    
    /**
     * 
     * @throws ServiceClientException 
     */
    protected void loadService() throws ServiceClientException
    {
        try
        {
            /**
             * 
             */
            this.serviceClient.connect();

            this.loadTransactionList();

       } 
       catch (Exception ex) 
       {
            this.showError("Error obteniendo el Perfil Bancario", ex.getMessage() );
       }
    }
    
    
    
    /**
     * 
     * @param evt 
     */
    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
        // TODO add your handling code here:        
        DialogLoading loading = this.buildLoading();
        CustomWorker worker = new CustomWorker( CustomWorker.FILTER_TRANSACTION_LIST, this, loading);
        worker.execute();
        loading.setVisible(true);
    }//GEN-LAST:event_buttonFilterActionPerformed

    private void buttonRevertedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRevertedActionPerformed
        // TODO add your handling code here:
        DialogLoading loading = this.buildLoading();
        CustomWorker worker = new CustomWorker(CustomWorker.REVERT_TRANSACTION, this, loading);
        worker.execute();
        loading.setVisible(true);
    }//GEN-LAST:event_buttonRevertedActionPerformed

    private void buttonCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCierreActionPerformed
        // TODO add your handling code here:
        ClosingOperationFrame ClosingOperationForm = new ClosingOperationFrame();
        ClosingOperationForm.show();
        
        
    }//GEN-LAST:event_buttonCierreActionPerformed

    
    /**
     * 
     * @throws comcodex.ServiceClientException
     */
    public void filterTransactionList() throws ServiceClientException
    {
        try
        {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            
            TransactionQuery query = new TransactionQuery();
            
            if( !"".equals(this.textboxBeginDate.getText().trim()) )
                query.beginDate = formatter.parse(this.textboxBeginDate.getText().trim());
            
            if( !"".equals(this.textboxEndDate.getText().trim()) )
                query.endDate = formatter.parse(this.textboxEndDate.getText().trim());
            
           
            Transaction[] transactions = this.serviceClient.listTransactions(query);
            
            TransactionListBoxModel model = new TransactionListBoxModel();
            model.fill(transactions);
            this.listboxTransactions.setModel(model);
            
        }
        catch(Exception ex)
        {
            //"Error en el filtro, revise las fechas, deben ser dd/mm/yyy"
            //this.showError(ex.getMessage());
            throw new ServiceClientException("Error en el filtro, revise las fechas, deben ser dd/mm/yyy");
        }
    }
    
    public void revertTransaction() throws ServiceClientException
    {
        
        try{
            
            if (this.listboxTransactions.getSelectedIndex() >= 0) {
               
                TransactionDisplayItem transactionDisplayItemSelected = (TransactionDisplayItem) this.listboxTransactions.getSelectedValue();
                Transaction transaction = transactionDisplayItemSelected.getValue();
                
                if (transaction != null) {
                    
                    if(transaction.status == comcodex.Transaction.STATUS_OK){
                        
                        Transaction transactionClient = this.serviceClient.revertTransaction(transaction); 
                        
                        if(transactionClient.status == comcodex.Transaction.STATUS_REVERT){
                            
                            JOptionPane.showMessageDialog(this, "La transacción fue revertida exitosamente.");
                            this.labelTitleStatusValue.setText( this.getLabelStatus( transaction.status ) );
                            
                            // Actualizar listado
                            DialogLoading loading = this.buildLoading();
                            
                            CustomWorker worker = new CustomWorker(CustomWorker.FILTER_TRANSACTION_LIST, this, loading);
                            
                            worker.execute();
                            
                            loading.setVisible(true);
                            
                        }else{
                            
                            this.showError("La transacción no pudo ser revertida.");
                        }
                        
                    }else{
                        
                        this.showError("La transacción debe estar pagada.");
                    }

                }

            }
            
            
            //
            
        }catch(Exception ex){
            throw new ServiceClientException("Error al intentar revertir la operacion indicada.");
        }
        
    }
    
    /**
     * 
     * @return 
     */
    public DialogLoading buildLoading()
    {
        DialogLoading loading = new DialogLoading(this, true);
        loading.setLocationRelativeTo(this);
        return loading;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateTransaction;
    private javax.swing.JButton buttonFilter;
    private javax.swing.JButton buttonLoadTransaction;
    private javax.swing.JButton buttonUpdateTransction;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelTitleAmount;
    private javax.swing.JLabel labelTitleAmountValue;
    private javax.swing.JLabel labelTitleCardNumber;
    private javax.swing.JLabel labelTitleCardNumberValue;
    private javax.swing.JLabel labelTitleConcept;
    private javax.swing.JLabel labelTitleConceptValue;
    private javax.swing.JLabel labelTitleDate;
    private javax.swing.JLabel labelTitleDateValue;
    private javax.swing.JLabel labelTitleDevice;
    private javax.swing.JLabel labelTitleDeviceValue;
    private javax.swing.JLabel labelTitleOperation;
    private javax.swing.JLabel labelTitlePayDate;
    private javax.swing.JLabel labelTitlePayDateValue;
    private javax.swing.JLabel labelTitlePayInfo;
    private javax.swing.JLabel labelTitlePayer;
    private javax.swing.JLabel labelTitlePayerIdentity;
    private javax.swing.JLabel labelTitlePayerIdentityValue;
    private javax.swing.JLabel labelTitlePayerValue;
    private javax.swing.JLabel labelTitleStatus;
    private javax.swing.JLabel labelTitleStatusValue;
    private javax.swing.JList listboxTransactions;
    private javax.swing.JPanel panelQr;
    private javax.swing.JTextField textboxBeginDate;
    private javax.swing.JTextField textboxEndDate;
    // End of variables declaration//GEN-END:variables

 
}
